excluded:
  - "*resource_bundle_accessor*" # SwiftPM Generated
  - ".build/*"

opt_in_rules:
  # - missing_docs
  # - empty_count
  # - empty_string
  - toggle_bool
  - unused_optional_binding
  - valid_ibinspectable
  - modifier_order
  - first_where
  - fatal_error_message
  - force_unwrapping

disabled_rules:
  - identifier_name
  - function_body_length
  - force_cast
  - force_unwrapping
  - file_length
  - cyclomatic_complexity
  - force_try
  - type_body_length
  - todo # Use // TODO: is allowed
